/** @type {import('tailwindcss').Config} */
export default {
  content: ['./index.html', './src/**/*.{vue,js}'],
  theme: {
    extend: {
      colors: {
        background: '#f7f9fb',
        surface: '#f7f9fb',
        'surface-bright': '#f7f9fb',
        'surface-container-lowest': '#ffffff',
        'surface-container-low': '#f2f4f6',
        'surface-container': '#eceef0',
        'surface-container-high': '#e6e8ea',
        'surface-container-highest': '#e0e3e5',
        'surface-variant': '#e0e3e5',
        'on-surface': '#191c1e',
        'on-background': '#191c1e',
        'on-surface-variant': '#444651',
        outline: '#757682',
        'outline-variant': '#c5c5d3',
        primary: '#00236f',
        'primary-container': '#1e3a8a',
        'primary-fixed': '#dce1ff',
        'on-primary': '#ffffff',
        'on-primary-container': '#90a8ff',
        'on-primary-fixed': '#00164e',
        secondary: '#00687a',
        'secondary-container': '#57dffe',
        'secondary-fixed': '#acedff',
        'secondary-fixed-dim': '#4cd7f6',
        'on-secondary': '#ffffff',
        'on-secondary-fixed': '#001f26',
        'on-secondary-fixed-variant': '#004e5c',
        tertiary: '#00311f',
        'tertiary-container': '#004a31',
        'tertiary-fixed': '#6ffbbe',
        'on-tertiary-fixed': '#002113',
        'on-tertiary-fixed-variant': '#005236',
        error: '#ba1a1a',
        'error-container': '#ffdad6',
        'on-error-container': '#93000a',
        warning: '#f59e0b',
        'inverse-surface': '#2d3133',
        'inverse-on-surface': '#eff1f3',
        'inverse-primary': '#b6c4ff',
      },
      borderRadius: {
        card: '1.5rem',
        control: '0.5rem',
      },
      boxShadow: {
        ambient: '0 4px 20px rgba(30, 58, 138, 0.05)',
        popover: '0 10px 30px rgba(30, 58, 138, 0.10)',
      },
      fontFamily: {
        sans: ['Inter', 'Arial', 'sans-serif'],
      },
      maxWidth: {
        container: '1440px',
      },
    },
  },
  plugins: [],
}
